### ISSUE TITLE
Feature request: configure tuned custom profiles in the module

### ISSUE THREAD

**Issue by ubellavance** [jcpunk/puppet-tuned#1]
Similar to this: https://github.com/thias/puppet-tuned/pull/15

**Comment by jcpunk** [comment]
I'm not sure how this would work in practice.

It is possible to load scripts that interrogate the system and return values (cf. powersave profile) which could itself have other file dependencies.  So dropping in a managed INI style file could work, it would be an incomplete implementation.

I'm inclined to suggest folks use `stdlib::manage` to generate the ini file in hiera.  It would be a bit ugly, but doesn't lead people into thinking this module supports the whole feature set.

```yaml
stdlib::manage:
  file:
    /usr/lib/tuned/custom-profile:
      ensure: directory
      owner: root
      group: root
      mode: "0644"
    /usr/lib/tuned/custom-profile/tuned.conf:
      ensure: file
      owner: root
      group: root
      mode: "0644"
      content: "[main]\ninclude=virtual-guest\n[sysctl]\nvm.dirty_ratio=30\n"
      notify: Class[tuned]
```
